export const ALBUM_ADDED_SHOPPING_CART = "ALBUM_ADDED_SHOPPING_CART";
export const TRACK_ADDED_SHOPPING_CART = "TRACK_ADDED_SHOPPING_CART";
export const SONGS_BOUGHT = "SONGS_BOUGHT";
export const REMOVE_SHOPPING_CART_SONGS = "REMOVE_SHOPPING_CART_SONGS";
